# Site settings
title: 'CJ & Matthew'
description: >
  CJ and Matthew are getting married in Kansas City!
  Learn about the nerdy couple,
  get info on the ceremony and reception,
  and find helpful hints to plan your visit to KC.
baseurl: ""
url: "http://www.cjandmatthew.com"

# Build settings
markdown: kramdown
exclude: [ 'README.md', 'Gemfile.lock', 'Gemfile', 'CNAME' ]
