# Site settings
title: 'CJ & Matthew'
description: >
  We are getting married in Kansas City on June 26, 2016!
  Learn about the nerdy couple,
  get info on the ceremony and reception,
  and find helpful hints to plan your visit to KC.
baseurl: /
url: "http://www.cjandmatthew.com"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
gems: [ jekyll-paginate ]
paginate: 5
exclude: [ 'README.md', 'Gemfile.lock', 'Gemfile', 'CNAME' ]
sass:
    style: compressed
