# Site settings
title: 'CJ & Matthew'
description: >
  We are getting married in Kansas City on June 26, 2016!
baseurl: /
url: "http://www.cjandmatthew.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
gems: [ jekyll-paginate ]
paginate: 5
exclude: [ 'README.md', 'Gemfile.lock', 'Gemfile', 'CNAME' ]
sass:
    style: compressed
